hf_home: /nvme/cache
model_config:
  batch_size: 1
  dtype: float16
  from_pretrained_kwargs: {}
  generation_kwargs:
    do_sample: true
    max_new_tokens: 256
    top_k: 0
    top_p: 0.92
  mirror_bucket_uri: s3://large-dl-models-mirror/models--stabilityai--stablelm-tuned-alpha-7b/main/
  mode:
    type: DeepSpeed
  name: stabilityai/stablelm-tuned-alpha-7b
  pipeline_cls: default
  prompt_format: null
  stopping_tokens: null
scaling_config:
  num_workers: 2
  num_gpus_per_worker: 1
  num_cpus_per_worker: 4